spring:
  application:
    name: driver-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/driver_db?useSSL=false&serverTimezone=UTC
    username: root
    password: asdfhcjsjffh
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  messages:
    basename: messages
    encoding: UTF-8
server:
  port: 8082