spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  data:
    mongodb:
      uri: ${MONGODB_URI}
  liquibase:
    enabled: ${LIQUIBASE_ENABLED}
    change-log: ${LIQUIBASE_CHANGELOG}

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server:
  port: ${SERVER_PORT}