spring:
  config:
    import: optional:file:.env[.properties]
  messages:
    basename: messages
    encoding: UTF-8
  application:
    name: ride_service
  data:
    mongodb:
      uri: mongodb://localhost:${DB_HOST}/${DB_NAME}
  liquibase:
    enabled: true
    change-log: db/changelog/changelog.xml
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS}
    consumer:
      group-id: ride-status
  artemis:
    mode: native
    user: admin
    password: admin
    broker-url: tcp://localhost:61616
  cloud:
    openfeign:
      client:
        config:
          finance-service:
            url: http://localhost:8084/api/v1/finance
          passenger-service:
            url: http://localhost:8081/api/v1/passengers
server:
  port: ${RIDE_SERVICE_PORT}