spring:
  application:
    name: passenger-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/passenger_db?useSSL=false&serverTimezone=UTC
    username: root
    password: asdfhcjsjffh
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  messages:
    basename: messages
    encoding: UTF-8
  cloud:
    openfeign:
      client:
        config:
          driver-service:
            url: http://localhost:8081/api/v1/rates
          ride-service:
            url: http://localhost:8083/api/v1/rides
server:
  port: 8081